# ExplodingEssentials
# Version 1.5
# UPDATE: Color in title is now fixed.
Server Admins:
  - ZeBigDipper
Welcome Title: 'Welcome To:'
Welcome Subtitle: 'My Server'
Title Color: 'gold'
Subtitle Color: 'aqua'